"""Initial migration.

Revision ID: 870235cb5761
Revises: 
Create Date: 2023-10-11 15:21:18.398343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870235cb5761'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Attribute',
    sa.Column('AttributeID', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('AttributeID'),
    sa.UniqueConstraint('Description')
    )
    op.create_table('Chain',
    sa.Column('ChainID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ChainID'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Product',
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('UPC', sa.String(length=50), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ProductID'),
    sa.UniqueConstraint('UPC')
    )
    op.create_table('SearchTerm',
    sa.Column('SearchTermID', sa.Integer(), nullable=False),
    sa.Column('Term', sa.String(length=255), nullable=False),
    sa.Column('ZipCode', sa.String(length=10), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('SearchTermID')
    )
    op.create_table('User',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.Text(), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('GroceryList',
    sa.Column('GroceryListID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('GroceryListID')
    )
    op.create_table('ProductAttribute',
    sa.Column('ProductAttributeID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('AttributeID', sa.Integer(), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['AttributeID'], ['Attribute.AttributeID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ProductID'], ['Product.ProductID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ProductAttributeID')
    )
    op.create_table('StoreLocation',
    sa.Column('StoreLocationID', sa.Integer(), nullable=False),
    sa.Column('ChainID', sa.Integer(), nullable=False),
    sa.Column('StoreAPIRef', sa.String(length=255), nullable=True),
    sa.Column('Address', sa.String(length=500), nullable=True),
    sa.Column('ZipCode', sa.String(length=10), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ChainID'], ['Chain.ChainID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('StoreLocationID')
    )
    op.create_table('UserPreference',
    sa.Column('PreferenceID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('AppSetting', sa.String(length=255), nullable=True),
    sa.Column('DietaryPreference', sa.String(length=255), nullable=True),
    sa.Column('ZipCode', sa.String(length=10), nullable=True),
    sa.Column('MaxTravelDistance', sa.Float(precision=2), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PreferenceID')
    )
    op.create_table('UserProductFavorite',
    sa.Column('FavoriteID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ProductID'], ['Product.ProductID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('FavoriteID')
    )
    op.create_table('GroceryListSearchTerm',
    sa.Column('GroceryListSearchTermID', sa.Integer(), nullable=False),
    sa.Column('GroceryListID', sa.Integer(), nullable=False),
    sa.Column('SearchTermID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['GroceryListID'], ['GroceryList.GroceryListID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SearchTermID'], ['SearchTerm.SearchTermID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('GroceryListSearchTermID')
    )
    op.create_table('StorePrice',
    sa.Column('StorePriceID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('StoreLocationID', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Float(precision=2), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ProductID'], ['Product.ProductID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['StoreLocationID'], ['StoreLocation.StoreLocationID'], ),
    sa.PrimaryKeyConstraint('StorePriceID')
    )
    op.create_table('SearchTermStorePrice',
    sa.Column('SearchTermStorePriceID', sa.Integer(), nullable=False),
    sa.Column('SearchTermID', sa.Integer(), nullable=False),
    sa.Column('StorePriceID', sa.Integer(), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['SearchTermID'], ['SearchTerm.SearchTermID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['StorePriceID'], ['StorePrice.StorePriceID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SearchTermStorePriceID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SearchTermStorePrice')
    op.drop_table('StorePrice')
    op.drop_table('GroceryListSearchTerm')
    op.drop_table('UserProductFavorite')
    op.drop_table('UserPreference')
    op.drop_table('StoreLocation')
    op.drop_table('ProductAttribute')
    op.drop_table('GroceryList')
    op.drop_table('User')
    op.drop_table('SearchTerm')
    op.drop_table('Product')
    op.drop_table('Chain')
    op.drop_table('Attribute')
    # ### end Alembic commands ###
