"""Initial migration.

Revision ID: a675f7383873
Revises: 
Create Date: 2023-10-14 18:11:50.366559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a675f7383873'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('UPC', sa.String(length=50), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ProductID'),
    sa.UniqueConstraint('UPC')
    )
    op.create_table('Search',
    sa.Column('SearchID', sa.Integer(), nullable=False),
    sa.Column('Term', sa.String(length=255), nullable=False),
    sa.Column('ZipCode', sa.String(length=10), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('SearchID')
    )
    op.create_table('Store',
    sa.Column('StoreID', sa.Integer(), nullable=False),
    sa.Column('Chain', sa.String(length=20), nullable=False),
    sa.Column('StoreAPIRef', sa.String(length=255), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Address', sa.String(length=500), nullable=True),
    sa.Column('ZipCode', sa.String(length=10), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('StoreID')
    )
    op.create_table('StorePrice',
    sa.Column('StorePriceID', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Float(precision=2), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.Column('SearchID', sa.Integer(), nullable=True),
    sa.Column('ProductID', sa.Integer(), nullable=True),
    sa.Column('StoreID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ProductID'], ['Product.ProductID'], ),
    sa.ForeignKeyConstraint(['SearchID'], ['Search.SearchID'], ),
    sa.ForeignKeyConstraint(['StoreID'], ['Store.StoreID'], ),
    sa.PrimaryKeyConstraint('StorePriceID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('StorePrice')
    op.drop_table('Store')
    op.drop_table('Search')
    op.drop_table('Product')
    # ### end Alembic commands ###
